### ISSUE TITLE
自己训练loss

### ISSUE THREAD

**Issue by zhangxiaopang88** [zhangyhuaee/KinD_plus#1]
您好，很感谢你能开源您的代码，我在自己训练模型，失去一般达到多少比较好？还有我觉得481对训练数据是不是太少了，我加了一些，会影响效果吗？@zhangyhuaee

还有论文中看到您使用NIQE这个指标在测试集测试，但是在github上，您说NIQE可以对已经训练好的模型提高精度。这一点不是很明白，您可以说的更详细一点吗

**Comment by zhangyhuaee** [comment]
您好，增加训练数据有助于提高模型的泛化能力，也会对当前结果产生一定的影响，其影响结果依据于你增加的训练图像的具体分布。我们不是说NIQE可以提升精度。本身NIQE的参数并不是一个固定不变的，针对特定的图像可以重新训练，以适应特定的目的，更多详细信息你可以看NIQE的论文。我们这里增加了一百张高清分辨率图像进行重新训练，是想提升其评价的鲁棒性，得到更加准确的评价值。MATLAB自带的NIQE也可以使用，它使用的模型也和NIQE作者提供的模型不一样，应该也是经过重新训练得到的。
