### ISSUE TITLE
Bad result when test on night-time low resolution images

### ISSUE THREAD

**Issue by TaQuangTu** [zhangyhuaee/KinD_plus#3]
When I test your model on KAIST dataset which includes 41K night-time images with resolution 640x512, results look more noise than origins. Below is a demo.
![orgin](https://user-images.githubusercontent.com/29690416/86534208-c8eb7200-bf00-11ea-8084-57328d31c0a2.png)
![kind](https://user-images.githubusercontent.com/29690416/86534216-ddc80580-bf00-11ea-94ca-29b8fe78ec6b.png)
How can I adjust parameters to get better results? Thank you!

**Comment by zhangyhuaee** [comment]
Due to the training dataset does not include this type of noise, the pretrained model can not deal with KAIST dataset. Maybe you can simulate this type of noise to synthesize a dataset, then retrain the model.
